language: node_js
node_js:
  - '0.10'
  - '0.8'

addons:
  code_climate:
    repo_token: 8648704d8b312e9f7e663f6a0f32519ef717cf85673029e6f2ddbe582c5386cc

branches:
  only:
    - master

before_script:
  - npm install -g grunt-cli istanbul coveralls codeclimate-test-reporter

script:
  - grunt test

after_script:
  - istanbul cover test/*_test.js --report lcovonly -- -R spec
  - codeclimate < ./coverage/lcov.info
  - cat ./coverage/lcov.info | coveralls
