language: node_js
node_js:
  - '0.10'
  - '0.8'

env:
  global:
    - CODECLIMATE_REPO_TOKEN=8648704d8b312e9f7e663f6a0f32519ef717cf85673029e6f2ddbe582c5386cc

before_script:
  - npm install -g grunt-cli coveralls codeclimate-test-reporter
  - chmod +x ./script/coverage.sh

script:
  - grunt test

after_script:
  - ./script/coverage.sh
  - codeclimate < ./coverage/lcov.info
  - cat ./coverage/lcov.info | coveralls
