language: node_js
node_js:
  - '0.10'
  - '0.8'

before_script:
  - npm install -g grunt-cli istanbul coveralls codeclimate-test-reporter

script:
  - grunt test

after_script:
  - exec < ./script/coverage.sh
  - codeclimate < ./coverage/lcov.info
  - cat ./coverage/lcov.info | coveralls
