language: node_js
node_js:
  - '0.10'
  - '0.8'
  
branches:
  only:
    - master
    
before_script:
  - npm install -g grunt-cli istanbul coveralls codeclimate-test-reporter

after_script:
  - istanbul cover test/*_test.js --report lcovonly -- -R spec
  - codeclimate < ./coverage/lcov.info
  - cat ./coverage/lcov.info | coveralls
